modify

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,21 +25,47 @@ jobs:
       with:
         creds: ${{ secrets.TSUTOMUTESTSECRET }} 
 
+        - name: Allow GitHub Actions IP ranges to access SCM
+        shell: pwsh
+        run: |
+          # GitHub ActionsのIPレンジを許可
+          $GITHUB_ACTIONS_IP_RANGES = (Invoke-RestMethod -Uri "https://api.github.com/meta").actions
+          Write-Output "Number of IP ranges: $($GITHUB_ACTIONS_IP_RANGES.Count)"
+          $priority = 100
+          foreach ($ip in $GITHUB_ACTIONS_IP_RANGES) {
+            Write-Output "Adding IP address: $ip with priority $priority"
+            az webapp config access-restriction add --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_APP_NAME }} --rule-name AllowGitHubActions_$ip --action Allow --ip-address $ip --priority $priority --scm-site true
+            if ($?) {
+              Write-Output "Successfully added IP address: $ip"
+            } else {
+              Write-Error "Failed to add IP address: $ip"
+            }
+            $priority++
+            # 最大数を設定してデバッグを制限する
+            if ($priority -ge 120) { break }
+          }
+  
     - name: Deploy to Azure Web App
       uses: azure/webapps-deploy@v2
       with:
-        app-name: ${{ secrets.AZURE_APP_NAME }}  # App Service の名前
-        slot-name: 'production'  # デプロイスロット
-        package: '.'  # デプロイするディレクトリまたはファイル
-
+          app-name: ${{ secrets.AZURE_APP_NAME }}  # App Service の名前
+          slot-name: 'production'  # デプロイスロット
+          package: '.'  # デプロイするディレクトリまたはファイル
+  
     - name: Remove GitHub Actions IP ranges from SCM access
       shell: pwsh
       run: |
-        # デプロイ後にIPレンジの許可を取り消す
-        $GITHUB_ACTIONS_IP_RANGES = (Invoke-RestMethod -Uri "https://api.github.com/meta").actions
-        foreach ($ip in $GITHUB_ACTIONS_IP_RANGES) {
-          az webapp config access-restriction remove --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_APP_NAME }} --rule-name AllowGitHubActions_$ip --scm-site true  # --identity オプションを削除
-        }
-
+          # デプロイ後にIPレンジの許可を取り消す
+          $GITHUB_ACTIONS_IP_RANGES = (Invoke-RestMethod -Uri "https://api.github.com/meta").actions
+          foreach ($ip in $GITHUB_ACTIONS_IP_RANGES) {
+            Write-Output "Removing IP address: $ip"
+            az webapp config access-restriction remove --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_APP_NAME }} --rule-name AllowGitHubActions_$ip --scm-site true
+            if ($?) {
+              Write-Output "Successfully removed IP address: $ip"
+            } else {
+              Write-Error "Failed to remove IP address: $ip"
+            }
+          }
+  
     - name: Logout from Azure
       run: az logout
